In [1]:
import numpy as np

In [57]:
B = np.array([[1,1,0,1,0],[1,1,0,1,0],[1,1,0,1,0],[0,0,1,0,1],[0,0,1,0,1]])
Bvals,Bvecs = np.linalg.eig(B)
BTvals, BTvecs = np.linalg.eig(B.T)

In [79]:
B = np.array([[1,1,0,1,0],
              [1,1,0,1,0],
              [1,1,0,1,0],
              [0,0,1,0,1],
              [0,0,1,0,1]])

Bvals, Bvecs = np.linalg.eig(B)
idx = np.argmax(Bvals)
q = Bvecs[:, idx]
q = -q

BTvals, BTvecs = np.linalg.eig(B.T)
idx2 = np.argmax(BTvals)
v = BTvecs[:,idx2]
v = v/(q@v)

lam=Bvals.max()

print(q,v,q@v)


[0.51544118 0.51544118 0.51544118 0.31856017 0.31856017] [0.53622646 0.53622646 0.33140618 0.53622646 0.33140618] 0.9999999999999999


In [80]:
P = np.zeros((5,5))
for i in range(5):
    for j in range(5):
        P[i,j] = B[i,j]*v[i]/(lam*v[j])
P

array([[0.38196601, 0.38196601, 0.        , 0.38196601, 0.        ],
       [0.38196601, 0.38196601, 0.        , 0.38196601, 0.        ],
       [0.23606798, 0.23606798, 0.        , 0.23606798, 0.        ],
       [0.        , 0.        , 0.61803399, 0.        , 0.61803399],
       [0.        , 0.        , 0.38196601, 0.        , 0.38196601]])

In [87]:
p = np.array([q[i]*v[i] for i in range(5)])
p

array([0.2763932 , 0.2763932 , 0.17082039, 0.17082039, 0.10557281])

In [88]:
P@p

array([0.2763932 , 0.2763932 , 0.17082039, 0.17082039, 0.10557281])

In [89]:
lam

2.6180339887498945

In [90]:
1/2*(3+np.sqrt(5))

2.618033988749895